config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'cidadaos#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cidadaos, except: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cidadao.rb
class Cidadao < ApplicationRecord
  has_one :endereco, dependent: :destroy
  accepts_nested_attributes_for :endereco
  has_one_attached :photo

  validates :nome, presence: true
  validates :sobrenome, presence: true
  validates :cpf, length: { is: 11 }, presence: true, uniqueness: true
  validates :cns, length: { is: 15 }, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  validates :telefone, presence: true, length: { minimum: 10 }, uniqueness: true
  validates :data_nascimento, presence: true
  validates :status, inclusion: { in: [ true, false ] }


  include PgSearch::Model
  pg_search_scope :buscar_por_dados_ou_endereco,
    against: [ :nome, :sobrenome, :cpf, :cns, :email, :data_nascimento, :telefone, :status ],
    associated_against: {
      endereco: [:cep, :logradouro, :complemento, :bairro, :cidade, :uf]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/models/endereco.rb
class Endereco < ApplicationRecord
  belongs_to :cidadao

  validates :cep, presence: true
  validates :logradouro, presence: true
  validates :cidade, presence: true
  validates :bairro, presence: true
  validates :uf, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/cidadaos_controller.rb
class CidadaosController < ApplicationController
  before_action :set_cidadao, only: [:show, :edit, :update]

  def index
    if params[:query].present?
      @cidadaos = Cidadao.buscar_por_dados_ou_endereco(params[:query])
    else
      @cidadaos = Cidadao.order('nome').all
    end
  end

  def show
    @endereco = @cidadao.endereco
  end

  def new
    @cidadao = Cidadao.new
    @cidadao.build_endereco
  end

  def create
    @cidadao = Cidadao.new(cidadao_params)
    account_sid = ENV['account_sid']
    auth_token = ENV['auth_token']
    @client = Twilio::REST::Client.new(account_sid, auth_token)
    if @cidadao.save
      @client.messages.create(       
                            messaging_service_sid: 'MGda2782dac34791e45af2ccd26e6f8ec4',   
                            to: "+55#{@cidadao.telefone}",
                            body: 'Você foi cadastrado na plataforma de munícipes.'
                            )
    CidadaoMailer.with(cidadao: @cidadao).email_cadastro.deliver_now                      
      redirect_to cidadao_path(@cidadao)
      flash[:notice] = 'Email e sms de confirmação enviados ao munícipe.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    account_sid = ENV['account_sid']
    auth_token = ENV['auth_token']
    @client = Twilio::REST::Client.new(account_sid, auth_token)
    if @cidadao.update(cidadao_params)
      @client.messages.create(       
                            messaging_service_sid: 'MGda2782dac34791e45af2ccd26e6f8ec4',   
                            to: "+55#{@cidadao.telefone}",
                            body: 'Seu cadastro foi atualizado na plataforma Munícipes. Por favor, cheque suas informações no seu email. Obrigado.'
                            )
      CidadaoMailer.with(cidadao: @cidadao).email_cadastro_atualizado.deliver_now
      redirect_to cidadao_path(@cidadao)
      flash[:notice] = 'Munícipe atualizado com sucesso.'
    else
      render :edit
      flash[:notice] = 'Algo deu errado. Tente novamente mais tarde.'
    end
  end

  private
  
  def set_cidadao
    @cidadao = Cidadao.find(params[:id])
  end

  def cidadao_params
    params.require(:cidadao).permit(:nome, :sobrenome, :cpf, :cns, :email, :data_nascimento, :telefone, :status, :photo, endereco_attributes: [:cep, :logradouro, :complemento, :bairro, :cidade, :uf, :codigo_ibge])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cidadaos/_form.html.erb
<div class="my-card-show">
  <div class="justify-between mb-2">
    <a class="simple-button" href="/cidadaos/" role="button">Lista de Munícipes</a>
  </div>
  <%= simple_form_for @cidadao, url: url_path do |f| %>
    <h2 class="mb-4">Dados pessoais</h2>
      <div class="row">
        <div class="col-4">
          <%= f.input :nome,
                      placeholder: "nome",
                      required: true,
                      autofocus: true,
                      input_html: { autocomplete: "nome" } %>
        </div>
        <div class="col-8">
          <%= f.input :sobrenome,
                      placeholder: "sobrenome completo",
                      required: true,
                      autofocus: true,
                      input_html: { autocomplete: "sobrenome" } %>                    
        </div>
        <div class="col-4">
          <%= f.input :data_nascimento, as: :string ,
                      required: true,
                      input_html: { type: 'date', autocomplete: "data_nascimento" } %>
        </div>
        <div class="col-4">
          <%= f.input :cpf,
            placeholder: "seu cpf",
            required: true,
            size: 11,
            input_html: { autocomplete: "cpf" } %>
        </div>
        <div class="col-4">
          <%= f.input :cns,
            placeholder: "seu cns",
            required: true,
            size: 15,
            input_html: { autocomplete: "cns"} %>
        </div>
        <div class="col-7">
          <%= f.input :email,
                      placeholder: "seuemail@exemplo.com",
                      required: true,
                      autofocus: true,
                      input_html: { autocomplete: "email" } %>
        </div>
        <div class="col-5">
          <%= f.input :telefone,
            placeholder: "(00) 0000-0000 com DDD",
            required: true,
            input_html: { autocomplete: "telefone", class:'telefone-masked'  } %>
        </div>
        <div class="col-6 mt-5">
          <%= f.collection_radio_buttons :status, [[true, 'Ativo'] ,[false, 'Inativo']],:first, :last, required: true %> 


        </div>
        <div class="col-6">
          <%= f.input :photo, as: :file %>
        </div>
      </div>
      <hr class="my-3">
      <div>
        <%= f.fields_for :endereco do |ff| %>
          <h2 class="mb-4">Endereço</h2>
          <div class="row g-3">
            <div class="col-md-2">
              <%= ff.input :cep,
                          placeholder: "seu cep",
                          required: true,
                          autofocus: true,
                          input_html: { autocomplete: "cep", class:'cep-masked cep' } %>
            </div>
            <div class="col-md-2">
              <%= ff.input :uf, collection: [["AC"],
                                            ["AL"],
                                            ["AP"],
                                            ["AM"],
                                            ["BA"],
                                            ["CE"],
                                            ["DF"],
                                            ["ES"],
                                            ["GO"],
                                            ["MA"],
                                            ["MT"],
                                            ["MS"],
                                            ["MG"],
                                            ["PA"],
                                            ["PB"],
                                            ["PR"],
                                            ["PE"],
                                            ["PI"],
                                            ["RJ"],
                                            ["RN"],
                                            ["RS"],
                                            ["RO"],
                                            ["RR"],
                                            ["SC"],
                                            ["SP"],
                                            ["SE"],
                                            ["TO"]],
                          label_method: :first, value_method: :first,
                          placeholder: "",
                          required: true,
                          input_html: { autocomplete: "uf" } %>
            </div>
            <div class="col-4">
              <%= ff.input :cidade,
                          id: "cidade",
                          placeholder: "sua cidade",
                          required: true,
                          autofocus: true,
                          input_html: { autocomplete: "cidade" } %>
            </div>
            <div class="col-4">
              <%= ff.input :bairro ,
                          id: "bairro",
                          placeholder: "seu bairro",
                          class: "form-pequeno",
                          required: true,
                          input_html: { autocomplete: "bairro" } %>
            </div>
            <div class="col-6">
              <%= ff.input :logradouro,
                          id: "logradouro",
                          placeholder: "seu logradouro",
                          required: true,
                          input_html: { autocomplete: "logradouro" } %>
            </div>
            <div class="col-3">
              <%= ff.input :complemento,
                          id: "complemento",
                          placeholder: "complemento (se existir)",
                          required: true,
                          input_html: { autocomplete: "complemento" } %>        
            </div>
            <div class="col-3">
              <%= ff.input :codigo_ibge,
                          id: "codigo_ibge",
                          placeholder: "seu código ibge",
                          required: true,
                          input_html: { autocomplete: "complemento" } %>        
            </div>
          </div>
        <% end %>
      </div>
    <%= f.submit "Adicionar Munícipe", class:"button-orange mt-2" %>
  <% end %>
</div>

app/views/cidadaos/edit.html.erb
<%= render 'form', url_path: cidadao_path %>

app/views/cidadaos/index.html.erb
<div class="my-card-index">
  <h1>Lista de Munícipes</h1>
  <div class="justify-between mt-4 mb-2">
    <%= form_tag(cidadaos_path, method: :get) do %>
      <%= text_field_tag :query,
                params[:query],
                as: :nome
              %>
      <%= submit_tag "Buscar", class: "button-orange-sm", remote: true %>        
    <% end %>
    <a class="simple-button" href="/cidadaos/new" role="button">Novo Munícipe</a>
  </div>
  <table class="styled-table-index">
    <thead>
      <tr>
        <th>Nome Completo</th>
        <th>CPF</th>
        <th>CNS</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <% @cidadaos.each do |cidadao| %>
        <tr onclick="location.href='<%= cidadao_path(cidadao) %>'">
          <td><%= cidadao.nome %> <%= cidadao.sobrenome %></td>
          <td><%= cidadao.cpf.unpack('A3A3A3A2').join('-') %></td>
          <td><%= (cidadao.cns) %></td>
          <td><%= cidadao.status? ? 'Ativo' : 'Inativo' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/cidadaos/new.html.erb
<%= render 'form', url_path: cidadaos_path %>

app/views/cidadaos/show.html.erb
<div class="show-container">
  <div class="profile-card">
    <% if @cidadao.photo.present? %>
        <%= cl_image_tag @cidadao.photo.key %>
    <% else %>
        <%= image_tag "avatar-img.png", style:'height: 150px; width: 150px; border-radius: 50%;' %>
    <% end %>
    <hr>
    <p><%= @cidadao.nome.titleize %> <%= @cidadao.sobrenome.titleize %></p>

    <table class="styled-table-vertical">
      <tr>
        <th>CPF</th>
        <td><%= @cidadao.cpf.unpack('A3A3A3A2').join('-') %></td>
      </tr>
      <tr>
        <th>Data de Nascimento</th>
        <td><%= @cidadao.data_nascimento.strftime("%d/%m/%y") %></td>
      </tr>
      <tr>
        <th>Status</th>
        <td><%= @cidadao.status? ? 'Ativo' : 'Inativo' %></td>
      </tr>
    </table>
  </div>
</div>

<div class="my-card-show">
  <div class="justify-between mb-3">
    <a class="simple-button" href="/cidadaos/" role="button">Lista de Munícipes</a>
    <a class="simple-button" href='<%= edit_cidadao_path(@cidadao) %>' role="button">Editar Munícipe</a>
  </div>
  <h2>Dados do Munícipe</h2>
  <table class="styled-table-show">
    <tr>
      <th>Nome Completo:</th>
      <td><%= @cidadao.nome.titleize %> <%= @cidadao.sobrenome.titleize %></td>
    </tr>
    <tr>
      <th>CPF:</th>
      <td><%= @cidadao.cpf.unpack('A3A3A3A2').join('-') %></td>
    </tr>
    <tr>
      <th>CNS:</th>
      <td><%= @cidadao.cns %></td>
    </tr>
    <tr>
      <th>Data de Nascimento:</th>
      <td><%= @cidadao.data_nascimento.strftime("%d/%m/%y") %></td>
    </tr>
    <tr>
      <th>Telefone:</th>
      <td><%= @cidadao.telefone %></td>
    </tr>
    <tr>
      <th>E-mail:</th>
      <td><%= @cidadao.email %></td>
    </tr>
    <tr>
      <th>Status:</th>
      <td><%= @cidadao.status? ? 'Ativo' : 'Inativo' %></td>
    </tr>
  </table>
</div>

<div class="my-card-show">
  <h2>Endereço do Munícipe</h2>
  <table class="styled-table-show">
    <tr>
      <th>Logradouro:</th>
      <td><%= @cidadao.endereco.logradouro %></td>
    </tr>
    <tr>
      <th>Complemento:</th>
      <td><%= @cidadao.endereco.complemento %></td>
    </tr>
    <tr>
      <th>Bairro:</th>
      <td><%= @cidadao.endereco.bairro %></td>
    </tr>
    <tr>
      <th>Cidade:</th>
      <td><%= @cidadao.endereco.cidade %></td>
    </tr>
    <tr>
      <th>UF:</th>
      <td><%= @cidadao.endereco.uf %></td>
    </tr>
    <tr>
      <th>Cep:</th>
      <td><%= @cidadao.endereco.cep %></td>
    </tr>
    <tbody>
      <tr>
      </tr>
    </tbody>
  </table>
  <table class="styled-table-show">
    <thead>
      <tr>
      </tr>
    </thead>
    <tbody>
      <tr>
      </tr>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MunicipesTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="d-flex flex-column mt-3 container justify-content-center">
  <div class="p-2 align-self-center mb-3">
    <h1 class="text-center mt-2">MUNÍCIPES</h1>
  </div>
    <div class="p-2 align-self-center">
      <a class="btn btn-home" href="cidadaos/" role="button">Munícipes</a>
    </div>
    <div class="p-2 align-self-center">
      <a class="btn btn-home" href="cidadaos/new" role="button">Novo Munícipe</a>
    </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon bg-dark fixed-top">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <i class="fas fa-user-check"></i>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Munícipes", root_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Novo Munícipe", new_cidadao_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "avatar-img.png", class: "avatar dropdown-toggle mx-2", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link text-white" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>